FROM xtrime/telegram-api-server:latest

RUN apt update && apt install -y autoconf build-essential \
    && pecl install xdebug \
    && apt clean

ADD dev/xdebug.ini $PHP_INI_DIR/conf.d/xdebug.ini

EXPOSE 9504
EXPOSE 9003

ENTRYPOINT php server.php --docker
