FROM xtrime/telegram-api-server:latest

RUN pecl install xdebug \
    && echo "" >> "$PHP_INI_DIR/conf.d/xdebug.ini" \
    && echo "zend_extension=xdebug.so" >> "$PHP_INI_DIR/conf.d/xdebug.ini"

EXPOSE 9504

ENTRYPOINT php server.php --docker